#!/usr/bin/env python3
"""Regenerate the theme palettes from upstream Omarchy (specs/review.md#theme).

Every theme in basecamp/omarchy ships a `colors.toml` with the same 24 keys —
the file flutter_omarchy reads at ~/.local/state/omarchy/current/theme/colors.toml.
This transcribes each one into a `:root[data-theme="<slug>"]` block of `--om-*`
custom properties, so the palettes stay a faithful copy of upstream and never a
hand-tuned fork of it. `app.css` binds its semantic names onto `--om-*`; nothing
here knows what a colour is *for*.

Needs the `gh` CLI, authenticated. Run it to pick up new upstream themes:

    uv run python scripts/fetch_omarchy_themes.py
"""

from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

REPO = "basecamp/omarchy"
STATIC = Path(__file__).resolve().parent.parent / "src/anki_assistant/web/static"

# The keys app.css binds to, in the order they are written out. `orange` and `brown`
# are missing from a few themes; the fallback keeps every block the same shape.
KEYS = [
    "accent",
    "selection",
    "muted",
    "background",
    "dark_background",
    "darker_background",
    "lighter_background",
    "foreground",
    "dark_foreground",
    "light_foreground",
    "bright_foreground",
    "red",
    "yellow",
    "orange",
    "green",
    "cyan",
    "blue",
    "magenta",
    "bright_red",
    "bright_yellow",
    "bright_green",
    "bright_cyan",
    "bright_blue",
    "bright_magenta",
]
FALLBACKS = {"orange": "yellow"}

# Used when the user has expressed no preference, picked by prefers-color-scheme.
DEFAULTS = {"dark": "tokyo-night", "light": "catppuccin-latte"}


def gh(path: str) -> str:
    """Read a file from the upstream repo through the gh CLI."""
    out = subprocess.run(
        ["gh", "api", f"repos/{REPO}/contents/{path}"],
        capture_output=True,
        text=True,
        check=True,
    )
    import base64

    return base64.b64decode(json.loads(out.stdout)["content"]).decode()


def theme_slugs() -> list[str]:
    out = subprocess.run(
        ["gh", "api", f"repos/{REPO}/contents/themes", "--jq", ".[].name"],
        capture_output=True,
        text=True,
        check=True,
    )
    return sorted(out.stdout.split())


def parse(toml: str) -> dict[str, str]:
    """colors.toml is flat `key = "value"` lines; a real TOML parser is overkill."""
    return dict(re.findall(r'^(\w+)\s*=\s*"([^"]+)"', toml, re.M))


def label(slug: str) -> str:
    return " ".join(w.capitalize() for w in slug.split("-"))


def main() -> None:
    themes = []
    for slug in theme_slugs():
        raw = parse(gh(f"themes/{slug}/colors.toml"))
        if "background" not in raw:
            continue  # not a palette
        mode = "light" if raw.get("mode") == "light" else "dark"
        colors = {k: raw.get(k) or raw[FALLBACKS[k]] for k in KEYS if k in raw or k in FALLBACKS}
        themes.append({"slug": slug, "label": label(slug), "mode": mode, "colors": colors})

    css = [
        "/* Omarchy theme palettes — generated by scripts/fetch_omarchy_themes.py, do not edit.",
        "",
        f"   A faithful transcription of the {len(themes)} colors.toml files in {REPO}: the same",
        "   file flutter_omarchy reads. app.css binds its semantic names (--accent, --flag,",
        "   --ok, …) onto these; a new theme is a new block here and nothing else. */",
        "",
    ]

    def block(selector: str, t: dict) -> None:
        css.append(f"{selector} {{")
        css.append(f"  color-scheme: {t['mode']};")
        for k, v in t["colors"].items():
            css.append(f"  --om-{k.replace('_', '-')}: {v};")
        css.append("}")
        css.append("")

    fallback = next(t for t in themes if t["slug"] == DEFAULTS["dark"])
    css.append("/* Bare :root, so a missing or unknown data-theme still paints a full palette")
    css.append(f'   rather than nothing. Same values as [data-theme="{fallback["slug"]}"]. */')
    block(":root", fallback)

    for t in themes:
        css.append(f"/* {t['label']} */")
        block(f':root[data-theme="{t["slug"]}"]', t)
    (STATIC / "themes.css").write_text("\n".join(css))

    js = [
        "/* Omarchy theme index — generated by scripts/fetch_omarchy_themes.py, do not edit.",
        "   One entry per palette block in themes.css; drives the picker in column 1. */",
        "",
        '"use strict";',
        "",
        "const THEMES = [",
    ]
    for t in themes:
        js.append(f'  {{ slug: "{t["slug"]}", label: "{t["label"]}", mode: "{t["mode"]}" }},')
    js.append("];")
    js.append("")
    js.append("/* Used until the user picks one, chosen by prefers-color-scheme. */")
    dflt = ", ".join(f'{k}: "{v}"' for k, v in DEFAULTS.items())
    js.append(f"const DEFAULT_THEME = {{ {dflt} }};")
    js.append("")
    (STATIC / "themes.js").write_text("\n".join(js))

    dark = sum(t["mode"] == "dark" for t in themes)
    light = len(themes) - dark
    print(f"{len(themes)} themes ({dark} dark, {light} light) -> themes.css, themes.js")


if __name__ == "__main__":
    main()
